#!/usr/bin/env bash
# That is one way of publishing your website pages to your server.

if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

if [ -z "$path_to_ssh_key" ]; then
    scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
else
    scp -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~/"
fi