#!/usr/bin/env bash
# That is another way of publishing your website pages to your server.
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
	# Install Nginx
	apt-get update
	apt-get install -y nginx
fi

# Configure Nginx
echo "server {
    listen 80;

    location / {
        root /var/www/html;
        index test.html;
    }
}" > /etc/nginx/sites-available/default

# Create a custom HTML page
echo "Hello World!" > /var/www/html/test.html

# Restart Nginx
service nginx restart
