#!/usr/bin/env bash
# This script is for creating a custom 404 page for your Nginx server.
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
	# Install Nginx
	apt-get update
	apt-get install -y nginx
fi

# Configure Nginx
echo "server {
    listen 80;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Restart Nginx
service nginx restart
