#!/usr/bin/env bash
# That is another way of publishing your website pages to your server.
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
	# Install Nginx
	apt-get update
	apt-get install -y nginx
fi

server_name=$(hostname | cut -d'-' -f2-)

# Configure Nginx
echo "server {
    listen 80;

	add_header X-Served-By $server_name;

    location / {
        root /var/www/html;
        index test.html;
    }

    location /redirect_me {
		rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Create a custom HTML page
echo "Hello World!" > /var/www/html/test.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Restart Nginx
service nginx restart
