#!/usr/bin/env bash
# Configuring a fresh new Ubuntu machine with HAproxy as a load balancer

# Check if HAproxy is installed
if ! command -v haproxy &> /dev/null; then
	apt-get update -y
	apt-get install -y haproxy
fi

# Configure HAproxy init script
echo "# Defaults file for HAProxy
#
# This is sourced by both, the initscript and the systemd unit file, so do not
# treat it as a shell script fragment.

# Change the config file location if needed
CONFIG=\"/etc/haproxy/haproxy.cfg\"

# Enable the HAProxy init script
ENABLED=1

# Add extra flags here, see haproxy(1) for a few options
#EXTRAOPTS="-de -m 16"" > /etc/default/haproxy

# Configure HAproxy
echo "global
	# Global settings

defaults
	# Default settings

frontend front_end
	# Frontend configuration

		bind *:80
		mode http
		default_backend web_servers

backend web_servers
	# Backend configuration

		mode http
		balance roundrobin
		server webserver1 100.26.11.29:80 check
		server webserver2 34.207.61.191:80 check
" > /etc/haproxy/haproxy.cfg

# Start HAproxy
sudo service haproxy restart
