#!/usr/bin/env bash
# This script creates a backup of all MySQL databases
# Get the current date in the desired format
DATE=$(date +%d-%m-%Y)

# Set the backup file name
BACKUP_FILE="backup.sql"

# Set the compressed archive name
ARCHIVE_NAME="$DATE.tar.gz"

# Set the MySQL user and password
MYSQL_USER="root"
MYSQL_PASSWORD="$1"

# Dump all MySQL databases to the backup file
mysqldump -u $MYSQL_USER -p$MYSQL_PASSWORD --all-databases > $BACKUP_FILE

# Compress the backup file to a tar.gz archive
tar -czvf $ARCHIVE_NAME $BACKUP_FILE

# Remove the backup file
rm $BACKUP_FILE
