#!/usr/bin/env bash
# printing numbers twenty times with while
i=1
while [ "$i" -lt "21" ]; do
	case "$i" in
		4) printf "%d\nbad luck from China\n" "$i" ;;
		9) printf "%d\nbad luck from Japan\n" "$i" ;;
		17) printf "%d\nbad luck from Italy\n" "$i" ;;
		*) echo "$i" ;;
	esac
	i=$((i + 1))
done
