#!/usr/bin/env bash
# Setting up a firewall

# Check if ufw is installed
if ! command -v ufw &> /dev/null; then
	# Install Nginx
	apt-get update
	apt-get install -y ufw
fi


# Reset ufw
sudo ufw enable

# Denying everything incoming and allowing outgoing
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allowing SSH, HTTP, HTTPS-SSL
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw reload
