#!/usr/bin/bash
# configuring ip addresses of server's hosts file
cp /etc/hosts ~/hosts.new
echo "127.0.0.2        localhost" > /etc/hosts
echo "8.8.8.8        facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
