#!/usr/bin/env bash
# configuring ip addresses of server's hosts file
cp /etc/hosts ~/hosts.new
echo "127.0.0.2        localhost" > ~/hosts.new
echo "8.8.8.8        facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
